// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace StackTraceExplorer
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidStackTraceExplorerToolWindowPackageString = "0485ea98-864e-461f-945f-3c8f9c994842";
        public static Guid guidStackTraceExplorerToolWindowPackage = new Guid(guidStackTraceExplorerToolWindowPackageString);

        public const string guidStackTraceExplorerToolWindowPackageCmdSetString = "8de831e0-1853-4232-8c10-da7fac5a2b54";
        public static Guid guidStackTraceExplorerToolWindowPackageCmdSet = new Guid(guidStackTraceExplorerToolWindowPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int StackTraceExplorerToolWindowCommandId = 0x0100;
    }
}