name: StackTraceExplorer

on:
  push:
    branches:
      - main
      - 'feature/**'

env:
  version: '4.0.${{ github.run_number }}'
  repoUrl: ${{ github.server_url }}/${{ github.repository }}

jobs:
  build:
    name: 🛠️ Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Update Assembly Version
        uses: dannevesdantas/set-version-assemblyinfo@v.1.0.0
        with:
          version: ${{ env.version }}

      - name: Update Vsix Version (VS2019)
        uses: cezarypiatek/VsixVersionAction@1.2
        with:
          version: ${{ env.version }}
          vsix-manifest-file: 'StackTraceExplorer.VS2019\source.extension.vsixmanifest'

      - name: Update Vsix Version (VS2022)
        uses: cezarypiatek/VsixVersionAction@1.2
        with:
          version: ${{ env.version }}
          vsix-manifest-file: 'StackTraceExplorer.VS2022\source.extension.vsixmanifest'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: NuGet restore
        run: nuget restore StackTraceExplorer.sln -ConfigFile nuget.config

      - name: Build VSIX
        run: msbuild StackTraceExplorer.sln /t:Rebuild /p:Configuration=Release
        env:
          DeployExtension: False

      - name: Publish Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: StackTraceExplorer
          path: |
            **\*.vsix
            publish-manifest.*.json
            readme.md

  release:
    if: github.ref_name == 'main'
    name: 🚀 Release
    needs: build
    runs-on: windows-latest
    environment: Release
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          merge-multiple: true

      - name: Tag release
        id: tag_release
        uses: mathieudutour/github-tag-action@v6.2
        with:
          custom_tag: '${{ env.version }}'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_release.outputs.new_tag }}
          name: ${{ steps.tag_release.outputs.new_tag }}
          body: ${{ steps.tag_release.outputs.changelog }}
          artifacts: "**/*.vsix"
          skipIfReleaseExists: true

      - name: Publish to Marketplace - VS2019
        uses: cezarypiatek/VsixPublisherAction@1.1
        with:
          extension-file: ${{ github.workspace }}/StackTraceExplorer.VS2019/bin/release/StackTraceExplorer.VS2019.vsix
          publish-manifest-file: StackTraceExplorer/publish-manifest.VS2019.json
          personal-access-code: ${{ secrets.VS_PUBLISHER_ACCESS_TOKEN }}

      - name: Publish to Marketplace - VS2022
        uses: cezarypiatek/VsixPublisherAction@1.1
        with:
          extension-file: ${{ github.workspace }}/StackTraceExplorer.VS2022/bin/release/StackTraceExplorer.VS2022.vsix
          publish-manifest-file: StackTraceExplorer/publish-manifest.VS2022.json
          personal-access-code: ${{ secrets.VS_PUBLISHER_ACCESS_TOKEN }}

      - name: Publish to Open VSIX Gallery - VS2019
        run: |
          curl -L 'https://www.vsixgallery.com/api/upload?repo=${{ env.repoUrl }}&issuetracker=${{ env.repoUrl }}/issues' -F 'file=@"StackTraceExplorer/StackTraceExplorer.VS2019/bin/release/StackTraceExplorer.VS2019.vsix"'

      - name: Publish to Open VSIX Gallery - VS2022
        run: |
          curl -L 'https://www.vsixgallery.com/api/upload?repo=${{ env.repoUrl }}&issuetracker=${{ env.repoUrl }}/issues' -F 'file=@"StackTraceExplorer/StackTraceExplorer.VS2022/bin/release/StackTraceExplorer.VS2022.vsix"'